# Generated by Django 2.0 on 2018-03-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(default='설명가능인공지능', max_length=50)),
                ('datetime', models.DateTimeField()),
                ('content', models.TextField()),
                ('image_raw', models.ImageField(upload_to='AutomaticNews/%Y/%m/%d')),
                ('image_predict', models.ImageField(upload_to='AutomaticNews/%Y/%m/%d')),
                ('report_pdf', models.FileField(upload_to='AutomaticNews/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DemoResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('professor', models.CharField(max_length=45)),
                ('research_on', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('department', models.TextField()),
                ('education', models.TextField()),
                ('career', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('testImage', models.ImageField(default='noImage', upload_to='member')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('contentk', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('Institutions', models.CharField(max_length=45)),
                ('Authors', models.CharField(max_length=200, null=True)),
                ('Publication_title', models.CharField(max_length=200, null=True)),
                ('Publication_link', models.CharField(max_length=200, null=True)),
                ('Sourcecode', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='RelatedProject/')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='submenu',
            name='topmenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.TopMenu'),
        ),
        migrations.AddField(
            model_name='relatedproject',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='publication',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='project',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='patent',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='notice',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='news',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='member',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='lab',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='greeting',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='github',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='demoresource',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='community',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
        migrations.AddField(
            model_name='autonews',
            name='submenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu'),
        ),
    ]
