# Generated by Django 2.0.3 on 2018-03-20 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180320_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_korean', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.AutoNews')),
                ('submenu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.SubMenu')),
            ],
        ),
    ]
