# Generated by Django 2.0.3 on 2018-03-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_companylist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companylist',
            old_name='company_korean',
            new_name='company_eng',
        ),
        migrations.RemoveField(
            model_name='companylist',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companylist',
            name='submenu_id',
        ),
        migrations.AddField(
            model_name='companylist',
            name='company_kor',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
