# Generated by Django 2.0.3 on 2018-03-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180320_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patent',
            old_name='writer',
            new_name='inventor',
        ),
        migrations.RenameField(
            model_name='patent',
            old_name='content',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='image',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='content',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='writer',
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patent',
            name='nation',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='publication',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
