# Generated by Django 2.0.3 on 2018-03-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180321_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='image',
        ),
    ]
